import './globals.css'
import { Lato } from "@next/font/google";

const roboto = Lato  ({
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
